### PR TITLE
use the v4 api endpoint

### PR DESCRIPTION
**Pull request by ryanahall**
@alainmeier thanks for the quick merge on the last pr.

Like I mentioned earlier, here's the v4 endpoing version. I've renamed verifications to people and question_set to question_sets to be consistent with the ruby library. I've also converted all hard tabs to soft tabs with tabstop set to 2 characters as per the last pr. Finally, I changed the minor version number because these are breaking changes, though you may want to change the major version since the api endpoint was updated.

Let me know what you think.

Thanks,
Ryan

### CODE REVIEW

**Comment by alainmeier** [comment]
This is great, will test it soon. In the meantime, can you please make the version `4.0.0` for the package? We like the major version number to correspond with the API version.

**Comment by alainmeier** [comment]
:+1:

**Comment by ryanahall** [comment]
Thanks again @alainmeier! Do you have any plans to upload 4.0.0 to pypi?

**Comment by alainmeier** [comment]
Definitely, hoping to get that pushed in a couple hours

**Comment by ryanahall** [comment]
great news! thanks!

**Pull request merged**
